enableTelemetry: false

logFilters:
  - code: YN0032
    level: discard
  - code: YN0076
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.14.1.cjs

npmMinimalAgeGate: 4320